development:
  adapter: postgresql
  database: development
  encoding: unicode
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: test
  encoding: unicode
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: production
  encoding: unicode
  pool: 5
  timeout: 5000
